    IDEAL
    SEGMENT image
    ASSUME CS:image,DS:image,ES:image,SS:image
    ORG     100h
start:
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
    jmp     ahead
ahead:
    nop
    ENDS
    END     start
